language: java
jdk:
  - openjdk8
sudo: true
dist: xenial
addons:
  apt:
    update: true
cache:
  directories:
    - $HOME/.m2

before_install:
  - rvm install 2.6.0
  - rvm use 2.6.0
  - sudo apt-get -y install nodejs-dev node-gyp libssl1.0-dev
  - sudo apt-get -y install npm
install:
  - gem install pdd -v 0.20.5
script:
  - set -e
  - mvn clean install -Pqulice --errors --batch-mode
  - mvn clean
  - pdd -f /dev/null
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"