language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - npm config set registry http://127.0.0.1:8080
  - mvn clean test
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - openjdk8
node_js:
  - "13"