language: java
jdk:
  - openjdk8
sudo: true
dist: bionic
addons:
  apt:
    update: true
cache:
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get -y install npm nodejs

script:
  - set -e
  - npm config set registry http://127.0.0.1:8080
  - mvn clean test
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"